version: '3'

services:
  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80
      - 2222:2222
    depends_on: 
      - mysql
    volumes:
       - ~/projects/drupal/:/var/www/sites/
  
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: drupaladm1n
    volumes:
      - ~/projects/databases/:/var/lib/mysql
      - drupal_files:/var/www/sites/

volumes:
  drupal_files:
  databases:
